### ISSUE TITLE
GmapsFx loading with a warning and not giving directions

### ISSUE THREAD

**Issue by jizang58** [dlsc-software-consulting-gmbh/GMapsFX#187]
Hi,

For a little project I have to make a javafx application where I can show the user the route from one location to another one. Like in Gmaps. I searched a bit and found gmapsfx and implemented the Library in my code so the map is loaded, but there is one problem it is watermarked which not really is a bad thing because this is a school project, but whenever I open the app it comes with a warning screen like below:

[enter image description here][1]

  [1]: https://i.stack.imgur.com/qhCYT.png

https://github.com/rterp/GMapsFX/issues/149 here it states that when I use a specific constructor It should fix this problem but it still did not help me with it.

Furthermore, I tried to implement the navigation from point a to b like here https://rterp.wordpress.com/2016/08/22/mapping-directions-with-javafx-using-the-gmapsfx-directions-api/
But it does not work for me. I am still an amateur so I don't really know what the problem is my console does not give any errors in eclipse. Maybe I am missing something can someone help me, please?

controllerclass:

    protected DirectionsService directionsService;
            protected DirectionsPane directionsPane;
            @FXML
            protected GoogleMapView mapView = new GoogleMapView("de-DE", "My-Google-Map-API-Key");;
            
            
            @FXML
            private TextField startAirportField;
    
            @FXML
            private TextField targetField;
    
            protected StringProperty from = new SimpleStringProperty();
            protected StringProperty to = new SimpleStringProperty();
            protected DirectionsRenderer directionsRenderer = null;
    
            @FXML
            private void toTextFieldAction() {
            	DirectionsRequest request = new DirectionsRequest(from.get(), to.get(), TravelModes.DRIVING);
                directionsRenderer = new DirectionsRenderer(true, mapView.getMap(), directionsPane);
                directionsService.getRoute(request, this, directionsRenderer);
            }
    
            @Override
            public void directionsReceived(DirectionsResult results, DirectionStatus status) {
            }
    
            
            public void initialize() {
                mapView.addMapInializedListener(this);
                to.bindBidirectional(startAirportField.textProperty());
                from.bindBidirectional(targetField.textProperty());
            }
            GoogleMap map ;
    
            @Override
            public void mapInitialized() {
                MapOptions options = new MapOptions();
    
    
                options.center(new LatLong(50.606189, -122.335842))
                        .zoomControl(true)
                        .zoom(12)
                        .overviewMapControl(false)
                        .mapType(MapTypeIdEnum.HYBRID);
                map = mapView.createMap(options);
                directionsService = new DirectionsService();
                directionsPane = mapView.getDirec();
            }

FXML

    <?xml version="1.0" encoding="UTF-8"?>
    
    <?import com.lynden.gmapsfx.GoogleMapView?>
    <?import javafx.scene.control.Button?>
    <?import javafx.scene.control.TextField?>
    <?import javafx.scene.layout.AnchorPane?>
    <?import javafx.scene.text.Text?>
    
    <AnchorPane id="AnchorPane" prefHeight="443.0" prefWidth="711.0" xmlns="http://javafx.com/javafx/11.0.1" xmlns:fx="http://javafx.com/fxml/1" fx:controller="Controllers.mapsViewController">
       <children>
          <GoogleMapView fx:id="mapView" layoutX="-311.0" layoutY="-244.0" prefWidth="490.0" AnchorPane.bottomAnchor="0.0" AnchorPane.leftAnchor="0.0" AnchorPane.rightAnchor="0.0" AnchorPane.topAnchor="0.0">
             <children>
                <Text fx:id="startAirport" layoutX="50.0" layoutY="20.0" strokeType="OUTSIDE" strokeWidth="0.0" text="Startflughafen" />
                <Text fx:id="targetAirport" layoutX="250.0" layoutY="20.0" strokeType="OUTSIDE" strokeWidth="0.0" text="Zielflughafen" />
                <TextField fx:id="startAirportField" layoutX="50.0" layoutY="25.0" />
                <TextField fx:id="targetField" layoutX="250.0" layoutY="25.0" />
                <Button fx:id="drawLine" layoutX="425.0" layoutY="25.0" mnemonicParsing="false" onAction="#toTextFieldAction" text="Suche" />
             </children></GoogleMapView>
       </children>
    </AnchorPane>

Log from eclipse:

    Dez 23, 2019 5:17:03 PM javafx.fxml.FXMLLoader$ValueElement processValue
    WARNING: Loading FXML document with JavaFX API of version 11.0.1 by JavaFX runtime of version 8.0.231
    Dez 23, 2019 5:17:04 PM javafx.fxml.FXMLLoader$ValueElement processValue
    WARNUNG: Loading FXML document with JavaFX API of version 11.0.1 by JavaFX runtime of version 8.0.231
    [JavaFX Application Thread] INFO com.lynden.gmapsfx.GoogleMapView - Alert: Hide directions called
    [JavaFX Application Thread] INFO com.lynden.gmapsfx.GoogleMapView - Alert: Hide directions called

**Comment by LorenzoTomesani** [comment]
did you find a solution?

**Comment by dlemmermann** [comment]
Which version are you using?

**Comment by LorenzoTomesani** [comment]
@dlemmermann had the same issues. i used java 15.0.1 and javafx15.0.1

**Comment by dlemmermann** [comment]
Which GMapsFX version?

**Comment by LorenzoTomesani** [comment]
2.12.0

**Comment by dlemmermann** [comment]
Please upgrade to 8.0.0. The project ownership has been transferred and I am the new maintainer. Hence also the group ID has changed. Please change your dependency to 

```xml
<dependency>
  <groupId>com.dlsc</groupId>
  <artifactId>GMapsFX</artifactId>
  <version>8.0.0</version>
</dependency>
```

**Comment by LorenzoTomesani** [comment]
i updated it, but it still gives me the same Alert. Where am i supposed to use the google api key? (if needed of course)
edit: it shows the map  with "For development purpose only"

**Comment by dlemmermann** [comment]
Just noticed that we have a Java 11+ branch. Please use 11.0.0. The Google API key is set like this:             googleMapView.setKey("AIzaSyDKjhxxxBygmij6QIqkOsgPZ5eKyk");

**Comment by dlemmermann** [comment]
It seems that the 11 release never arrived on Maven Central. Please add jcenter as another repository if you want to use it.

**Comment by Zeroxcharisma** [comment]
where can i find where i can edit this 
<dependency>
  <groupId>com.dlsc</groupId>
  <artifactId>GMapsFX</artifactId>
  <version>8.0.0</version>
</dependency>

**Comment by Zeroxcharisma** [comment]
> Please upgrade to 8.0.0. The project ownership has been transferred and I am the new maintainer. Hence also the group ID has changed. Please change your dependency to
> 
> ```
> <dependency>
>   <groupId>com.dlsc</groupId>
>   <artifactId>GMapsFX</artifactId>
>   <version>8.0.0</version>
> </dependency>
> ```

where can i find this in java project

**Comment by Zeroxcharisma** [comment]
My java version is 8 , what version of GMampsFX should i use ?

**Comment by dlemmermann** [comment]
Java 8 version: https://search.maven.org/artifact/com.dlsc/GMapsFX/8.0.0/jar

**Comment by Nesta-gitU** [comment]
I still have the exact same issues with java 11 and gmaps 11. did anyone find a solution
?

**Comment by nikelodeon2000** [comment]
If I use googleMapView.setKey("api-key"); in the initialize method the watermarks are gone for me.

**Comment by Nesta-gitU** [comment]
did you pay for a billing account on the google cloud website?

**Comment by nikelodeon2000** [comment]
I'm doing it for a University project and google gives you a free trial for 90 days, up to 300€. So no, I will cancel it after the free trial as well. Does anyone know how to properly protect my API key for a GMapsFX project?

**Comment by Nesta-gitU** [comment]
Same uni project I suppose. I need to do that too then

**Comment by Nesta-gitU** [comment]
btw yes there are some setting in the api dashboard for restricting usage of the key. Otherwise you would have to store it remotely but that won't work for our project since you need to send it to the TA eventually

**Comment by nikelodeon2000** [comment]
Yeah, I saw that but I'm not sure which protection method is the correct one for my project.
